### ISSUE TITLE
Thematic by GDB

### ISSUE THREAD

**Issue by kaerumy** [Sinar/awesome-dotmy-opendata-resources#1]
Another possibility is to also have resources by thematic area following GDB https://globaldatabarometer.org/

**Comment by samqi** [comment]
Noted on themes at [GDB](https://globaldatabarometer.org/research/countries-and-themes/) :
- Climate Action
- Company Info
- Land 
- Political Integrity
- Public Finance
- Public Procurement

**Comment by samqi** [comment]
As our data we have available are[ currently more on civic data, government data etc](https://github.com/Sinar/awesome-dotmy-opendata-resources/commit/0a4187fa9f378dc023696c3b5def4075f92770bb), I used the [data categories mentioned at Civic Switchboard guide](https://civic-switchboard.gitbook.io/guide/context-and-concepts/ways-of-thinking-about-data-open-data-civic-data) : 
> Open data as a concept is not associated with any one domain. However, two of the most prominent categories of open data are 1) [research ](https://www.nature.com/articles/sdata201618)and [science](https://mozillascience.github.io/open-data-primers/index.html), and 2) [government ](https://opendatapolicyhub.sunlightfoundation.com/why-open-data/)and [civic data](http://detroitcommunitytech.org/sites/default/files/librarypdfs/opening_data.pdf).

Will close this issue for now & reissue and open again when we have more data to suit these themes
