### ISSUE TITLE
Suggestion: Key Penang Statistics

### ISSUE THREAD

**Issue by philip-khor** [Sinar/awesome-dotmy-opendata-resources#2]
Would suggest adding [Key Penang Statistics](https://penanginstitute.org/resources/key-penang-statistics/) by [Penang Institute](https://penanginstitute.org/aboutus/the-institute/). 

The portal maintains a set of dashboards based on public data, but it can be a great way to get started on exploring what data is available publicly from government agencies. 

I would've PR-ed but wasn't sure which section this belongs to. 

(Disclaimer: I currently maintain these dashboards)

**Comment by samqi** [comment]
For now, I will place it under "Research" section and probably rework it in the future.
Thanks for letting me know you are the author and will be attributing your github profile for it. 

Will also look into a better mechanisms for the issue/PR moving forward
